### ISSUE TITLE
Provide sample data

### ISSUE THREAD

**Issue by vcaldas** [SingleMolecule/iSBatch#11]
Create a link in our server so the users can download and try the analysis.

**Comment by vcaldas** [comment]
@cmpunter  Do we have a server that we can allow public access to just a folder, so we can share the iSBacth sample data?

**Comment by cmpunter** [comment]
We can store it on the singlemolecule server in the lab (the same server as where our website is running on)

**Comment by vcaldas** [comment]
Added and the link in the main panel also added.
