### ISSUE TITLE
Macro Panel

### ISSUE THREAD

**Issue by vcaldas** [SingleMolecule/iSBatch#3]
Macro panel should behave as follows:
- Give a option (checkbox maybe) to operate that code in every selected file.
- The user indicate, via comboboxes, check box and textFields the Channel, the FileTag or a custom name.
- User selects where to save. If checkbox is selected "To database", the file generated is saved in the SAME folder of the input file. IF a folder is indicated, the file is exported to that folder and added a numeric index . [channel]myFileTag_0000.TIF

If the user provides a customName, it overrides the Tags in the combobox.(when searching)
- A list of files is provided and whatever is in the macro editor is executed in that SINGLE FILE.

If tables and ROIS are generated with this macro, the difference is in the extension.
[green]514.tif input.
output [green]514[custom].tif | [green]514[custom].roi |[green]514[custom].zip |[green]514[custom].table
table is a csv file.

**Comment by cmpunter** [comment]
* Regarding the option to operate code on every selected file, what is the alternative? If the user does not want to execute the macro on each file (so the checkbox is not checked) what should happen then?
* Which channels can be selected by the user? Currently the code first searches which channels exist below the selected node. Should the user be able to select multiple channels? Or should the user, in this case, run the macro multiple times (once for each selected channel)? How is the channel specified? Currently (in the importer code) this is specified as ```.*568.?\.tif``` for red channel (so test568a.tif is a valid red channel tif file. The file test568[tag].tif is NOT a valid red channel file.).
* What do you mean with 'save to database'? So the macro should save files in the same folder as the files where the macro runs on. Should the macro save the generated images/results tables/etc via IJ.save or should iSBatch code do this? How does iSBatch know which files opened by the macro should be saved? What if the macro opens multiple images/results tables/etc, what name should we give each file (multiple images for example)?
* How are filenames specified? The format for filenames changed a few times in the past and it seems to me that there is no consensus about this. So should it be [channel]name[tag].extension ? Take a look at the Importer code to see how filenames are currently specified.

Maybe what would help is an example macro. Can you give a few macro-examples? Also specify where the output should be specified.

**Comment by vcaldas** [comment]
* You wanted to create a macro to run on the database and developed several support codes for that. If the checkbox is not selected, then operates like you wanted. I just want to be able to run a macro that operates in 1 file, with 1 results table and 1 Roi manager for now.
* What do you mean by that? If the channel does not exist, it cannot be selected. If the user selects a channel, the macro runs for that channel. If the user selects "All" then the macro runs SEPARATELY for each channel. It is like running twice, but with the same selected parameters. 
* Channel is specified when you call node.getChannel. According to the filter implemented, there is no search in the name. The only time that the code checks for that is when it imports the raw data. After that, if a file is created from a red channel, then it will be red. Like 568.tif is red. So, 568_flat is also red. And WHATEVER568BLOB.Tif is also red. This is set when addint the file to the tree.
* Save to the database means that the file will be available in the Tree view and saved in the database. IF not, it will be exported to a selected folder and the names will be sequential.
* If want to save to the database, ask a folder name. In that folder all the results will be saved. It the macro creates 10 tables, then save all 10. If a macro creates several tables and images they have to have different names otherwise IJ won't handle then. So, same for us. If the user does not rename his tables when creating, not our problem. If you use WindowManager (from IJ API) you can detect what was created. After the run, check what was created and save in that folder. 
*Names of files and tables is not iSBAtch responsability. The user should state that in the macro. 
* Filenames are changing because the code is changing and new requirements are appearing.  And we don't have a proper handling for that. Maybe we should organize this again. The format [channel]name_tag didn't change. Not sure what you meant.

Use a macro recorder with any random operations and try to reproduce it. 
One example could be:
-----
run("Delete Slice");
run("Delete Slice");
run("Delete Slice");
run("Peak Finder", "use_discoidal_averaging_filter inner_radius=1 outer_radius=3 threshold=6 threshold_value=0 selection_radius=4 minimum_distance=8 stack");
run("Select All");
roiManager("Measure");
---

This example takes a image, alterates the image. Creates a ROI manager and a ResultsTable. 
So, all should be saved and the code starts with a single open image.

**Comment by cmpunter** [comment]
Clear! So the there will be three files that need to be saved. The original file (but now with a tag). The results table and all the roi's of the roiManager. Is this correct?

**Comment by vcaldas** [comment]
Yep. In this case yes. I think it is fair to assume this to start.
And the user has to indicate the tag!
I'm currently assuming that the names follow  [channel]name_tag.tif , [channel]name_tag.zip (for the rois) and  [channel]name_tag.csv for the table.

**Comment by vcaldas** [comment]
To avoid future problems. Leave the option in the dialog to call one image, one ROI Manager and one table. If the user dont specify anything, then it won't be previously open. 
I think this covers most of the usual cases.

**Comment by cmpunter** [comment]
It will be difficult to check if the macro created multiple images! The easy way is 

```java
IJ.open("Z:\\Victor\\PollymeraseCompetition\\PolymeraseCompetition\\TimeLapse\\DnaX_UmuC_001\\001 514.TIF");
String macro = "IJ.log(nImages);run(\"Gaussian Blur...\", \"sigma=2 slice\");";
IJ.runMacro(macro);
ImagePlus imp = IJ.getImage();
System.out.println(imp.changes);
```
So you can open an image, then run a macro on it and get the result (and check if the image was changed!).

Is this sufficient? Or do we need support for multiple images? I'm writing a wrapper ```MacroRunner```class for this.

**Comment by vcaldas** [comment]
Why don't you use a WindowManager.getImageCount() or WindowManager.getImageNames()?  Then you can check if images were created and save all of them. Or even compare the names that existed before and the ones created later.

The wapper sounds a great idea!
Did  you try using the already built in imageJ macro? 
IJ.run("Macro... ", "output=TIFF file=[] text1=[run("Subtract...", "value=207 stack"); ]");

So probably we will have to wrinte a Files[] as input and it will likely to be done!

**Comment by cmpunter** [comment]
There is a problem with using ```WindowManager.getImageCount()``` and ```WindowManager.getImageNames()```. When a macro is ran on an image then ```WindowManager.getImageCount()``` will correctly return 1. When the macro duplicates the input image you would expect two images. This is, unfortunately not the case : 

```java
IJ.open("Z:\\Victor\\PollymeraseCompetition\\PolymeraseCompetition\\TimeLapse\\DnaX_UmuC_001\\001 514.TIF");
String macro = "IJ.log(nImages); ";
IJ.runMacro(macro);
System.out.println(IJ.getImage());
		
for (String title : WindowManager.getImageTitles()) {
	ImagePlus i = WindowManager.getImage(title);
	System.out.println(i);
}
```

Correctly outputs : 

```
1
img[001 514.TIF (512x512x1x1x1)]
```

But when the macro code opens other images: 

```java
IJ.open("Z:\\Victor\\PollymeraseCompetition\\PolymeraseCompetition\\TimeLapse\\DnaX_UmuC_001\\001 514.TIF");
String macro = "IJ.log(nImages); run(\"Duplicate...\", \"title=test1\"); run(\"Duplicate...\", \"title=test2\");";
IJ.runMacro(macro);
System.out.println(IJ.getImage());
		
for (String title : WindowManager.getImageTitles()) {
	ImagePlus i = WindowManager.getImage(title);
	System.out.println(i);
}
```

The output is : 

```
1
img[test2 (512x512x1x1x1)]
img[test1 (512x512x1x1x1)]
img[test2 (512x512x1x1x1)]
```

This means that there is no reference to the original input image even though that image might have been manipulated.

**Comment by cmpunter** [comment]
A quick fix is to open the input image inside the macro code. So an open-statement will be appended to the macro code (as a prefix of course).

**Comment by cmpunter** [comment]
I just added the new macro runner. Please take a look at the macro runner class. This class contains all the logic for running macros. Especially the node filter is important since it decides which fileNodes will be considered for running a macro on. Also take a look at the runMacro method since this method contains all the logic for storing files.

**Comment by cmpunter** [comment]
By the way, I changed the Importer class slightly! 
```java
public void importFile(Node node, File file, String channel, String name) {
```
I removed the last argument ```path``` since this one is anyway taken from the ```File``` object that you supply. This also involves a little change in the ```FlattenOperation``` class since it uses this method,

**Comment by cmpunter** [comment]
Output folder option. So output all files to a specified folder instead of the default output folder.
The files should not be included in the tree when a output folder is specified!

**Comment by cmpunter** [comment]
I've added the output folder option. This has been tested.
