### ISSUE TITLE
Builder errors

### ISSUE THREAD

**Issue by cmpunter** [SingleMolecule/iSBatch#36]
Today I installed eclipse on a new computer. When I import iSBatch I get a few error/warnings that the build tool cannot be found. I think this should be resolved since every person who downloads the code will get this error. (Project properties - Builders)

**Comment by vcaldas** [comment]
Could you copy the errors?
Or this is the sole message?

**Comment by cmpunter** [comment]
![image](https://cloud.githubusercontent.com/assets/8568019/8495009/5eeb5eda-216a-11e5-899a-a9d9195a10a5.png)

**Comment by cmpunter** [comment]
Imported as GitHub project but should be automatically be recognized as a Maven project

**Comment by cmpunter** [comment]
How should the iSBatch project be imported from github? First locally as github and then as a Maven project in Eclipse? Would this resolve the issue?

When compiling and running iSBatch I get the following error which is related to my previous comment. When trying to run a second time everything seems to be fine though. It might be that it takes some time before Eclipse recognizes all the external libraries.
The error in my first command are still there.

![image](https://cloud.githubusercontent.com/assets/8568019/8495040/9f92cfa4-216a-11e5-86f4-8b1c3cc0cfdf.png)

**Comment by vcaldas** [comment]
The last version should be fix this issue.
