### ISSUE TITLE
Create operation button for the change point plugin / step fitter

### ISSUE THREAD

**Issue by cmpunter** [SingleMolecule/iSBatch#38]
StepFitter3 should be called. Before calling we need to open a results table. This can be done in the Operation code.

**Comment by cmpunter** [comment]
@vcaldas how are you handling the SMB plugins? Do you expect them to be included in ImageJ? I think we should include the step fitter plugin into the smb plugins. Where are the smb plugins located?

**Comment by vcaldas** [comment]
I'm provided them together with iSBatch - not inside.
In that way we can keep the development together but the update will be
done manually for now.

I do expect that ImageJ knows about their existence. The SMB plugins are in
a different repository.

We should think about a better structure later.

**Comment by cmpunter** [comment]
My last commit contains the step fitter operation
