### ISSUE TITLE
Load Button

### ISSUE THREAD

**Issue by vcaldas** [SingleMolecule/iSBatch#5]
The load button works on the first run. If a database is already open, the code is not refreshing properly the content.

**Comment by vcaldas** [comment]
Will be released in v0.3-beta

**Comment by vcaldas** [comment]
Do not close a issue without testing.

**Comment by cmpunter** [comment]
Of course I tested this before committing. I did the following : 
* Opening an existing database
* Create new database
* Reopen an existing database

Keep in mind that it takes some time (several seconds) to load a database. Meanwhile you see the old database tree structure. Did you experience any problem with the load-operation?

When can I close this issue then?

**Comment by vcaldas** [comment]
For some reason didn't work before but I tested now and works fine. My bad. sorry.
